import { serve } from "https://deno.land/std@0.190.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface BadgeRequest {
  type: "study_guide" | "devotional" | "assessment";
  title: string;
  subtitle?: string;
  completionDate?: string;
  userName?: string;
}

const handler = async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { type, title, subtitle, completionDate, userName }: BadgeRequest = await req.json();

    console.log("Generating badge for:", { type, title });

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY not configured");
    }

    // Create detailed prompt based on achievement type
    let prompt = "";
    
    switch (type) {
      case "study_guide":
        prompt = `Create a beautiful, professional achievement badge certificate with a modern design. The design should have:
- A gradient background from deep purple (#7c3aed) to lighter purple (#a855f7)
- Sacred geometry or elegant ornamental borders in gold/white
- Large bold text saying "${title}"
- Subtitle: "${subtitle || 'Study Guide Completed'}"
- User name: "${userName || 'Sacred Greeks Member'}"
- Date completed: "${completionDate || new Date().toLocaleDateString()}"
- A ribbon or medal icon at the top
- Elegant, celebratory design suitable for Instagram sharing (1080x1080px square format)
- Professional typography with clear hierarchy
- Inspirational elements like stars, laurels, or divine light rays
Make it feel special and worthy of sharing on social media.`;
        break;
        
      case "devotional":
        prompt = `Create a serene, spiritual achievement badge with:
- A peaceful gradient background from soft blue to warm cream
- Gentle light rays or sunrise imagery
- Large text: "${title}"
- Subtitle: "Daily Devotional Completed"
- User name: "${userName || 'Faithful Reader'}"
- An open book or praying hands icon
- Date: "${completionDate || new Date().toLocaleDateString()}"
- Calming, meditative design (1080x1080px square)
- Scripture-inspired decorative elements
- Soft, warm color palette
Perfect for sharing spiritual growth milestones.`;
        break;
        
      case "assessment":
        prompt = `Create an impressive achievement certificate badge with:
- A bold gradient background from purple to gold
- Professional academic or achievement-style design
- Large prominent text: "${title}"
- Subtitle: "${subtitle || 'Assessment Completed'}"
- User name: "${userName || 'Achievement Earner'}"
- A shield, star, or trophy icon
- Date: "${completionDate || new Date().toLocaleDateString()}"
- Sharp, modern design (1080x1080px square)
- Celebratory elements like confetti or stars
- Professional color scheme
Designed to celebrate personal growth and achievement.`;
        break;
    }

    // Call Lovable AI Gateway for image generation
    const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image-preview",
        messages: [
          {
            role: "user",
            content: prompt
          }
        ],
        modalities: ["image", "text"]
      })
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error("AI Gateway error:", errorText);
      throw new Error(`AI Gateway failed: ${aiResponse.status} - ${errorText}`);
    }

    const aiData = await aiResponse.json();
    console.log("AI response received");

    // Extract the generated image
    const imageUrl = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    
    if (!imageUrl) {
      throw new Error("No image generated by AI");
    }

    return new Response(
      JSON.stringify({ 
        success: true, 
        imageUrl,
        message: "Badge generated successfully"
      }),
      {
        status: 200,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  } catch (error: any) {
    console.error("Error generating badge:", error);
    return new Response(
      JSON.stringify({ 
        error: error.message || "Failed to generate badge",
        success: false
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);
